# Generated by Django 2.1.5 on 2019-01-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
