# Generated by Django 2.1.5 on 2019-01-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0008_auto_20190115_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
