# Generated by Django 2.1.5 on 2019-01-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0009_auto_20190115_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
